/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as AuthAuthLayoutImport } from './routes/auth/_authLayout'
import { Route as LayoutTransactionImport } from './routes/_layout/transaction'
import { Route as LayoutTopUpImport } from './routes/_layout/top-up'
import { Route as LayoutProfileImport } from './routes/_layout/profile'
import { Route as AuthAuthLayoutRegisterImport } from './routes/auth/_authLayout/register'
import { Route as AuthAuthLayoutLoginImport } from './routes/auth/_authLayout/login'
import { Route as LayoutServicesServiceNameImport } from './routes/_layout/services/$serviceName'

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthAuthLayoutRoute = AuthAuthLayoutImport.update({
  id: '/_authLayout',
  getParentRoute: () => AuthRoute,
} as any)

const LayoutTransactionRoute = LayoutTransactionImport.update({
  id: '/transaction',
  path: '/transaction',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTopUpRoute = LayoutTopUpImport.update({
  id: '/top-up',
  path: '/top-up',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProfileRoute = LayoutProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthAuthLayoutRegisterRoute = AuthAuthLayoutRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

const AuthAuthLayoutLoginRoute = AuthAuthLayoutLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

const LayoutServicesServiceNameRoute = LayoutServicesServiceNameImport.update({
  id: '/services/$serviceName',
  path: '/services/$serviceName',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/top-up': {
      id: '/_layout/top-up'
      path: '/top-up'
      fullPath: '/top-up'
      preLoaderRoute: typeof LayoutTopUpImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/transaction': {
      id: '/_layout/transaction'
      path: '/transaction'
      fullPath: '/transaction'
      preLoaderRoute: typeof LayoutTransactionImport
      parentRoute: typeof LayoutImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_authLayout': {
      id: '/auth/_authLayout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_layout/services/$serviceName': {
      id: '/_layout/services/$serviceName'
      path: '/services/$serviceName'
      fullPath: '/services/$serviceName'
      preLoaderRoute: typeof LayoutServicesServiceNameImport
      parentRoute: typeof LayoutImport
    }
    '/auth/_authLayout/login': {
      id: '/auth/_authLayout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLayoutLoginImport
      parentRoute: typeof AuthAuthLayoutImport
    }
    '/auth/_authLayout/register': {
      id: '/auth/_authLayout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthLayoutRegisterImport
      parentRoute: typeof AuthAuthLayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutTopUpRoute: typeof LayoutTopUpRoute
  LayoutTransactionRoute: typeof LayoutTransactionRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutServicesServiceNameRoute: typeof LayoutServicesServiceNameRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutTopUpRoute: LayoutTopUpRoute,
  LayoutTransactionRoute: LayoutTransactionRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutServicesServiceNameRoute: LayoutServicesServiceNameRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutLoginRoute: typeof AuthAuthLayoutLoginRoute
  AuthAuthLayoutRegisterRoute: typeof AuthAuthLayoutRegisterRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutLoginRoute: AuthAuthLayoutLoginRoute,
  AuthAuthLayoutRegisterRoute: AuthAuthLayoutRegisterRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/profile': typeof LayoutProfileRoute
  '/top-up': typeof LayoutTopUpRoute
  '/transaction': typeof LayoutTransactionRoute
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/services/$serviceName': typeof LayoutServicesServiceNameRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
}

export interface FileRoutesByTo {
  '/profile': typeof LayoutProfileRoute
  '/top-up': typeof LayoutTopUpRoute
  '/transaction': typeof LayoutTransactionRoute
  '/auth': typeof AuthIndexRoute
  '/': typeof LayoutIndexRoute
  '/services/$serviceName': typeof LayoutServicesServiceNameRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/top-up': typeof LayoutTopUpRoute
  '/_layout/transaction': typeof LayoutTransactionRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/_authLayout': typeof AuthAuthLayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_layout/services/$serviceName': typeof LayoutServicesServiceNameRoute
  '/auth/_authLayout/login': typeof AuthAuthLayoutLoginRoute
  '/auth/_authLayout/register': typeof AuthAuthLayoutRegisterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/profile'
    | '/top-up'
    | '/transaction'
    | '/auth'
    | '/'
    | '/auth/'
    | '/services/$serviceName'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/top-up'
    | '/transaction'
    | '/auth'
    | '/'
    | '/services/$serviceName'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/profile'
    | '/_layout/top-up'
    | '/_layout/transaction'
    | '/auth'
    | '/auth/_authLayout'
    | '/_layout/'
    | '/auth/'
    | '/_layout/services/$serviceName'
    | '/auth/_authLayout/login'
    | '/auth/_authLayout/register'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/_layout",
        "/auth"
      ]
    },
    "/_layout": {
      "filePath": "_layout.jsx",
      "children": [
        "/_layout/profile",
        "/_layout/top-up",
        "/_layout/transaction",
        "/_layout/",
        "/_layout/services/$serviceName"
      ]
    },
    "/_layout/profile": {
      "filePath": "_layout/profile.jsx",
      "parent": "/_layout"
    },
    "/_layout/top-up": {
      "filePath": "_layout/top-up.jsx",
      "parent": "/_layout"
    },
    "/_layout/transaction": {
      "filePath": "_layout/transaction.jsx",
      "parent": "/_layout"
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_authLayout",
        "/auth/"
      ]
    },
    "/auth/_authLayout": {
      "filePath": "auth/_authLayout.jsx",
      "parent": "/auth",
      "children": [
        "/auth/_authLayout/login",
        "/auth/_authLayout/register"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.jsx",
      "parent": "/_layout"
    },
    "/auth/": {
      "filePath": "auth/index.jsx",
      "parent": "/auth"
    },
    "/_layout/services/$serviceName": {
      "filePath": "_layout/services/$serviceName.jsx",
      "parent": "/_layout"
    },
    "/auth/_authLayout/login": {
      "filePath": "auth/_authLayout/login.jsx",
      "parent": "/auth/_authLayout"
    },
    "/auth/_authLayout/register": {
      "filePath": "auth/_authLayout/register.jsx",
      "parent": "/auth/_authLayout"
    }
  }
}
ROUTE_MANIFEST_END */
